-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.prompts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  act TEXT NOT NULL UNIQUE,
  prompt TEXT NOT NULL,
  category TEXT DEFAULT 'Uncategorized',
  tags TEXT DEFAULT '',
  source TEXT DEFAULT 'prompts.chat',
  is_favorite SMALLINT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: We don't strictly need FTS5 since we can use ILIKE for search, 
-- but if we want to optimize text search in PostgreSQL we would do:
-- CREATE INDEX idx_prompts_search ON prompts USING gin(to_tsvector('english', act || ' ' || prompt));
